In [5]:
import pandas as pd
import sqlite3
from pathlib import Path

# Lista de archivos CSV a cargar
csv_files = ['BD_Negocios_uno.csv', 'BD_Negocios_Dos.csv']
table_names = ['negocios_uno', 'negocios_dos']  # Nombres de las tablas en SQLite

# Crear conexión a la base de datos SQLite
try:
    conn = sqlite3.connect('bd_negocio2.db')
    print("Conexión a la base de datos SQLite 'bd_negocio2.db' establecida con éxito.")

    # Iterar sobre los archivos CSV y sus respectivos nombres de tabla
    for csv_file, table_name in zip(csv_files, table_names):
        # Verificar si el archivo existe
        if not Path(csv_file).is_file():
            print(f"Error: El archivo '{csv_file}' no se encuentra en el directorio.")
            continue
        
        try:
            # Leer el archivo CSV con delimitador punto y coma
            df = pd.read_csv(csv_file, sep=';', encoding='latin1', on_bad_lines='skip')
            print(f"Archivo '{csv_file}' cargado exitosamente con {len(df)} registros.")

            # Convertir el DataFrame a una tabla SQLite
            df.to_sql(table_name, conn, if_exists='replace', index=False)
            print(f"Tabla '{table_name}' creada en la base de datos con éxito.")

        except Exception as e:
            print(f"Error al procesar el archivo '{csv_file}': {str(e)}")

    # Confirmar los cambios y cerrar la conexión
    conn.commit()
    print("Todos los datos han sido procesados y guardados en 'bd_negocio2.db'.")

except Exception as e:
    print(f"Error al conectar con la base de datos: {str(e)}")

finally:
    conn.close()
    print("Conexión a la base de datos cerrada.")

Conexión a la base de datos SQLite 'bd_negocio2.db' establecida con éxito.
Error al procesar el archivo 'BD_Negocios_uno.csv': parser_f() got an unexpected keyword argument 'on_bad_lines'
Error al procesar el archivo 'BD_Negocios_Dos.csv': parser_f() got an unexpected keyword argument 'on_bad_lines'
Todos los datos han sido procesados y guardados en 'bd_negocio2.db'.
Conexión a la base de datos cerrada.

In [4]:
df.head()

,tipdoc,numdoc,fcre,monto_mes_ini,cuota_mes_ini,ncuota_mes_ini,tasa_mes_ini,saldo_mes_20151231,Flg_Refin_Jud_Cast_6m,per_perdida_6m,...,tipolocal,tipoactividad,actividadeconomica,tipovivienda,r_cuotapagada,NodeID,PredictedValue,PredictedProbability_1,PredictedProbability_2,SampleAssignment
0,1,10094125,20101108,7054.88,724.06,12,46.0,26048.85,NaN,NaN,...,Alquilado,Manufactura,FABRICACION DE PRENDAS DE VEST,De Familia,0.17,48.0,0.0,0.912150,0.087850,1.0
1,1,10095961,20151117,1000.00,198.40,6,77.0,857.94,0.0,201605.0,...,De Familia,Comercio,VENTA P/MENOR ALIMENTOS BEBIDA,De Familia,0.17,46.0,0.0,0.819512,0.180488,1.0
2,1,10096577,20150717,3000.00,450.20,8,60.0,6363.52,NaN,NaN,...,De Familia,Comercio,VENTA AL POR MENOR DE OTROS PR,De Familia,0.13,39.0,0.0,0.957640,0.042360,1.0
3,1,10097630,20091119,25000.00,1797.60,18,37.0,52589.96,NaN,NaN,...,Alquilado,Servicios,ACTIVIDADES DE FOTOGRAFIA,Propia Pagándola,0.29,48.0,0.0,0.912150,0.087850,1.0
4,1,10102896,20151107,1000.00,191.70,6,60.0,849.05,NaN,NaN,...,De Familia,Comercio,VENTA AL POR MAYOR DE OTROS PR,Alquilada,0.17,44.0,0.0,0.571429,0.428571,0.0

In [6]:
!pip install jupytext

Collecting jupytext
  Downloading jupytext-1.15.2-py3-none-any.whl (307 kB)
     ------------------------------------ 307.2/307.2 kB 761.4 kB/s eta 0:00:00
Requirement already satisfied: nbformat in c:\users\113167\anaconda3\lib\site-packages (from jupytext) (4.4.0)
Requirement already satisfied: pyyaml in c:\users\113167\anaconda3\lib\site-packages (from jupytext) (5.1.2)
Collecting toml (from jupytext)
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting markdown-it-py>=1.0.0 (from jupytext)
  Downloading markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
     -------------------------------------- 84.5/84.5 kB 674.8 kB/s eta 0:00:00
Collecting mdit-py-plugins (from jupytext)
  Downloading mdit_py_plugins-0.3.5-py3-none-any.whl (52 kB)
     -------------------------------------- 52.1/52.1 kB 536.5 kB/s eta 0:00:00
Collecting mdurl~=0.1 (from markdown-it-py>=1.0.0->jupytext)
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: typing_extensions>=3.7.4 in c:\users\113167\anaconda3\lib\site-packages (from markdown-it-py>=1.0.0->jupytext) (4.4.0)
Requirement already satisfied: ipython-genutils in c:\users\113167\anaconda3\lib\site-packages (from nbformat->jupytext) (0.2.0)
Requirement already satisfied: traitlets>=4.1 in c:\users\113167\anaconda3\lib\site-packages (from nbformat->jupytext) (4.3.3)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\113167\anaconda3\lib\site-packages (from nbformat->jupytext) (3.0.2)
Requirement already satisfied: jupyter-core in c:\users\113167\anaconda3\lib\site-packages (from nbformat->jupytext) (4.5.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\113167\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupytext) (19.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\113167\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupytext) (0.15.4)
Requirement already satisfied: setuptools in c:\users\113167\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupytext) (41.4.0)
Requirement already satisfied: six>=1.11.0 in c:\users\113167\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupytext) (1.12.0)
Requirement already satisfied: decorator in c:\users\113167\anaconda3\lib\site-packages (from traitlets>=4.1->nbformat->jupytext) (4.4.0)
Installing collected packages: toml, mdurl, markdown-it-py, mdit-py-plugins, jupytext
Successfully installed jupytext-1.15.2 markdown-it-py-2.2.0 mdit-py-plugins-0.3.5 mdurl-0.1.2 toml-0.10.2

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
!jupytext --to notebook sqlalchemy_database_operations_fixed.py

[jupytext] Reading sqlalchemy_database_operations_fixed.py in format py
[jupytext] Writing sqlalchemy_database_operations_fixed.ipynb